#!/usr/bin/env python3
"""
init_config.py — build your client_config.yaml by answering plain questions.

No YAML editing. Run this BEFORE the bootstrap. Uses only the Python standard
library, so it works in a fresh Cloud Shell with nothing installed.

  curl -O https://raw.githubusercontent.com/emilenols/scanner/main/init_config.py
  python3 init_config.py

It asks a handful of questions, sets all the technical fields to safe defaults
(region, model, thresholds, and the GDPR safety lock), leaves the document types
for the Drive Analysis step to propose, and writes ~/client_config.yaml.
"""
import os
import re
import sys

OUT = os.path.expanduser("~/client_config.yaml")


def slug(s, suffix=""):
    base = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    base = (base + suffix)[:30].rstrip("-")
    if base and not base[0].isalpha():
        base = "x" + base[:29]
    return base or "client-data-lake"


def ask(label, default=None, validator=None, help_text=None):
    if help_text:
        print(f"  ({help_text})")
    while True:
        suffix = f" [{default}]" if default else ""
        try:
            val = input(f"{label}{suffix}: ").strip()
        except EOFError:
            val = ""
        if not val and default is not None:
            val = default
        if not val:
            print("  -> required, please enter a value")
            continue
        if validator:
            ok, hint = validator(val)
            if not ok:
                print(f"  -> {hint}")
                continue
        return val


def v_project(s):
    ok = bool(re.match(r"^[a-z][a-z0-9-]{4,28}[a-z0-9]$", s))
    return ok, "6-30 chars, lowercase letters/digits/hyphens, start with a letter, no trailing hyphen"


def v_bucket(s):
    ok = bool(re.match(r"^[a-z0-9][a-z0-9._-]{1,61}[a-z0-9]$", s)) and s == s.lower()
    return ok, "3-63 chars, lowercase letters/digits/hyphens, globally unique"


def yq(s):
    """quote a YAML scalar safely"""
    return '"' + str(s).replace('"', "'") + '"'


def main():
    print("\n=== Build your scanner config ===")
    print("Answer each question and press Enter. Where a default is shown in")
    print("[brackets], just press Enter to accept it.\n")

    if os.path.exists(OUT):
        if ask(f"{OUT} already exists. Overwrite? (yes/no)", default="no").lower() not in ("y", "yes"):
            print("Keeping the existing file. Nothing changed.")
            return

    client = ask("Your company's legal name")
    engagement = ask("A reference for this engagement (anything you like)",
                     default="DATA-LAKE-2026")
    operator = ask("Who is running this scan (your name or team)")

    print()
    project = ask("A project ID for the cloud project", default=slug(client, "-data-lake"),
                  validator=v_project)
    bucket = ask("A storage bucket name (must be unique worldwide)",
                 default=slug(project, "-catalog-eu"), validator=v_bucket)
    folder = ask("The EXACT name of your mirror folder in Google Drive",
                 help_text="copy it character-for-character from drive.google.com")

    print()
    context = ask("One line describing your business",
                  help_text="e.g. 'Belgian commercial real estate leasing company'")

    print("\nWho signs off the document categories (a business owner is ideal):")
    ga_name = ask("  name")
    ga_role = ask("  role", default="Approver")
    print("Who runs the pilot review (often the person doing this setup):")
    gb_name = ask("  name", default=operator)
    gb_role = ask("  role", default="Execution Operator")

    sa_email = f"scanner-sa@{project}.iam.gserviceaccount.com"

    cfg = f"""# client_config.yaml — generated by init_config.py
# Technical fields are set to safe defaults. The document types are filled by
# the Drive Analysis step (walkthrough Part 5.3). Re-run init_config.py to redo.

client: {yq(client)}
engagement_ref: {yq(engagement)}
operator: {yq(operator)}

gcp:
  project_id: {yq(project)}
  region: "europe-west1"
  bucket: {yq(bucket)}
  service_account: "scanner-sa"

drive:
  source_folder: {yq(folder)}

taxonomy:
  system_context: {yq(context)}
  document_types:
    - "Unknown"          # the Drive Analysis (Part 5.3) proposes the real list
  languages: ["nl", "fr", "en", "mixed", "unknown"]

routing:
  model: "gemini-2.5-flash-lite"
  accept_threshold: 0.85
  review_threshold: 0.70
  fallback_model: "gemini-2.5-pro"

gdpr:
  pass1_legal_basis: "type-only classification, no PII persisted — no basis required"
  pass2_legal_basis_ref: null

gates:
  gate_a_approver: {{ name: {yq(ga_name)}, role: {yq(ga_role)} }}
  gate_b_approver: {{ name: {yq(gb_name)}, role: {yq(gb_role)} }}
"""
    with open(OUT, "w") as f:
        f.write(cfg)

    print(f"\n  Wrote {OUT}")
    print(f"  Project: {project}   Bucket: {bucket}   Folder: {folder}")
    print(f"  When the bootstrap finishes, you'll share '{folder}' with:")
    print(f"      {sa_email}")
    print("\nNext step — run the bootstrap:")
    print("  bash <(curl -s https://raw.githubusercontent.com/emilenols/scanner/main/setup.sh)")


if __name__ == "__main__":
    main()
